/**
 * Gemini Direct Image Generation Service
 *
 * Direct integration with Google's Gemini API for image generation
 * as an alternative to OpenRouter. Provides access to Gemini's free tier.
 *
 * @author AI Dungeon Master Team
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import { GeminiApiManager } from './gemini-api-manager';

interface GeminiImageGenerationRequest {
  prompt: string;
  referenceImage?: string; // base64 encoded image to use as reference
}

/**
 * Service class for direct Gemini image generation
 */
export class GeminiImageService {
  private geminiManager: GeminiApiManager;
  private readonly MODEL_NAME = 'gemini-2.0-flash-image-preview';
  private usageToday = 0;
  private readonly DAILY_FREE_LIMIT = 15; // Conservative estimate for free tier

  constructor() {
    this.geminiManager = new GeminiApiManager();
  }

  /**
   * Check if we can use the free tier today
   * @returns true if under daily limit
   */
  canUseFreeToday(): boolean {
    // Reset usage counter at start of new day
    const today = new Date().toDateString();
    const lastUsageDate = localStorage.getItem('gemini-image-last-usage-date');

    if (lastUsageDate !== today) {
      this.usageToday = 0;
      localStorage.setItem('gemini-image-last-usage-date', today);
      localStorage.setItem('gemini-image-usage-today', '0');
    } else {
      this.usageToday = parseInt(localStorage.getItem('gemini-image-usage-today') || '0', 10);
    }

    return this.usageToday < this.DAILY_FREE_LIMIT;
  }

  /**
   * Record successful usage
   */
  private recordUsage(): void {
    this.usageToday++;
    localStorage.setItem('gemini-image-usage-today', this.usageToday.toString());
  }

  /**
   * Get remaining free requests for today
   * @returns number of free requests remaining
   */
  getRemainingFreeRequests(): number {
    if (!this.canUseFreeToday()) {
      return 0;
    }
    return this.DAILY_FREE_LIMIT - this.usageToday;
  }

  /**
   * Generate an image using Gemini's direct API
   * @param request - Image generation request parameters
   * @returns Promise resolving to base64 encoded image data
   */
  async generateImage(request: GeminiImageGenerationRequest): Promise<string> {
    const { prompt, referenceImage } = request;

    // Check if we can use free tier
    if (!this.canUseFreeToday()) {
      throw new Error(
        `Gemini free tier limit exceeded for today (${this.DAILY_FREE_LIMIT} requests). ` +
        'Please try again tomorrow or use a paid alternative.'
      );
    }

    try {
      const result = await this.geminiManager.executeWithRotation(async (genAI: GoogleGenerativeAI) => {
        const model = genAI.getGenerativeModel({
          model: this.MODEL_NAME,
        });

        // Build the content based on whether we have a reference image
        let content;

        if (referenceImage) {
          // Multimodal request with reference image and text prompt
          content = [
            {
              text: prompt
            },
            {
              inlineData: {
                mimeType: 'image/png',
                data: referenceImage
              }
            }
          ];
        } else {
          // Text-only request
          content = prompt;
        }

        console.log('Generating image with Gemini direct API:', prompt);

        const response = await model.generateContent({
          contents: [{
            role: 'user',
            parts: typeof content === 'string' ? [{ text: content }] : content
          }]
        });

        const result = await response.response;

        // Check if response contains image data
        if (!result.candidates || result.candidates.length === 0) {
          throw new Error('No image generated by Gemini API');
        }

        const candidate = result.candidates[0];
        if (!candidate.content || !candidate.content.parts) {
          throw new Error('Invalid response format from Gemini API');
        }

        // Look for image data in the response
        let imageData = null;

        for (const part of candidate.content.parts) {
          if (part.inlineData && part.inlineData.data) {
            imageData = part.inlineData.data;
            break;
          }
        }

        if (!imageData) {
          throw new Error('No image data found in Gemini API response');
        }

        // Record successful usage
        this.recordUsage();

        console.log(`Successfully generated image with Gemini direct API. Remaining free requests today: ${this.getRemainingFreeRequests()}`);

        return imageData;
      });

      return result;
    } catch (error) {
      console.error('Error generating image with Gemini direct API:', error);

      // Provide more specific error messages for common issues
      if (error instanceof Error) {
        if (error.message.includes('quota') || error.message.includes('limit')) {
          throw new Error(
            'Gemini API quota exceeded. This may be due to rate limits or daily usage limits. ' +
            'Please try again later or use the OpenRouter fallback.'
          );
        }

        if (error.message.includes('429')) {
          throw new Error(
            'Gemini API rate limit exceeded. Please wait a moment before trying again.'
          );
        }
      }

      throw new Error(`Gemini image generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Get usage statistics for today
   * @returns Object containing usage stats
   */
  getUsageStats(): { used: number; limit: number; remaining: number } {
    return {
      used: this.usageToday,
      limit: this.DAILY_FREE_LIMIT,
      remaining: this.getRemainingFreeRequests()
    };
  }
}

// Export singleton instance
export const geminiImageService = new GeminiImageService();