/**
 * Cairn RPG System Configuration
 *
 * Configuration for Cairn, an ultra-light OSR adventure game inspired by Knave and Into the Odd.
 * Cairn features classless characters with three ability scores (STR, DEX, WIL), deadly combat,
 * and inventory-based resource management. The system emphasizes fast character creation,
 * fiction-first gameplay, and player agency.
 *
 * Key Features:
 * - Classless character creation with background traits
 * - Three ability scores: Strength, Dexterity, Willpower
 * - No character levels - progression through equipment and scars
 * - Roll-under saving throws (no modifiers)
 * - Anyone can cast spells from spellbooks
 * - Inventory slots drive resource management
 * - Deadly combat with critical damage to STR
 *
 * @module data/game-systems/cairn
 */

import { GameSystem, GameSystemConfig, CAIRN_ABILITY_SCORES } from '@/types/game-systems';

/**
 * Complete configuration for the Cairn RPG system.
 *
 * Cairn is designed for fast-paced, deadly adventures in mysterious fantasy settings.
 * The system strips away mechanical complexity to focus on player decision-making
 * and fictional positioning. With no classes or levels, characters are defined by
 * their equipment, scars, and the choices they make during play.
 *
 * @constant
 * @type {GameSystemConfig}
 */
export const CAIRN_CONFIG: GameSystemConfig = {
  /** Unique identifier for Cairn system */
  id: GameSystem.CAIRN,

  /** Full display name */
  name: 'Cairn',

  /** Short name for compact displays */
  shortName: 'Cairn',

  /** Brief description highlighting key features */
  description:
    'Ultra-light OSR adventure game. Classless characters with 3 abilities, deadly combat, and inventory-based resource management. Fast setup, fiction-first play.',

  /** Mountain emoji representing the mysterious, dangerous wilderness */
  icon: '⛰️',

  /** Creative Commons Attribution-ShareAlike license */
  license: 'CC-BY-SA',

  /** Link to Cairn's official website and license information */
  licenseUrl: 'https://cairnrpg.com',

  /** Complexity rating: 1 (simplest system) - minimal rules, fast to learn */
  complexity: 1,

  /** Descriptive tags for categorization and search */
  tags: ['OSR', 'Minimalist', 'Classless', 'Rules-Light', 'Deadly'],

  /** Genres that work well with Cairn's tone and mechanics */
  compatibleGenres: ['Dark Fantasy', 'Horror', 'Traditional Fantasy'],

  /** Cairn is classless - characters are defined by equipment and background */
  hasClasses: false,

  /** Cairn has no mechanical races - all characters use the same rules */
  hasRaces: false,

  /** Optional background traits and starting equipment define character origins */
  hasBackgrounds: true,

  /** Spellbooks contain spells that anyone can cast (no spell slots) */
  hasSpells: true,

  /** No feats or special abilities - characters gain scars and equipment */
  hasFeats: false,

  /** Ability score configuration for Cairn's three-attribute system */
  abilityScores: {
    /** Three core abilities: Strength, Dexterity, Willpower */
    scores: CAIRN_ABILITY_SCORES,

    /** Ability scores range from 3 (very weak) to 18 (exceptional) */
    scoreRange: {
      min: 3,
      max: 18,
    },

    /** Average score is 10 (generated by rolling 3d6) */
    averageScore: 10,

    /**
     * Cairn modifier formula: roll-under saves with no modifiers.
     * Players roll d20 and try to roll equal to or under their ability score.
     */
    modifierFormula: 'cairn',
  },

  /**
   * Level range: Cairn has no levels.
   * Characters progress through equipment acquisition and scars, not XP.
   * Set to 1-1 to indicate no level progression system.
   */
  levelRange: {
    min: 1,
    max: 1,
  },

  /** Dark slate gray theme color - evokes mysterious woods and ancient stones */
  color: '#2F4F4F',

  /** Background image path for Cairn system UI */
  backgroundImage: '/images/game-systems/cairn-bg.jpg',
};
