-- Create agent_checkpoints table for LangGraph state persistence
-- This replaces the custom IndexedDB messaging persistence with server-side state management

CREATE TABLE IF NOT EXISTS public.agent_checkpoints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id TEXT NOT NULL,
  checkpoint_id TEXT NOT NULL,
  parent_checkpoint_id TEXT,
  state JSONB NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),

  -- Ensure unique checkpoints per thread
  UNIQUE(thread_id, checkpoint_id)
);

-- Index for fast thread-based lookups
CREATE INDEX IF NOT EXISTS idx_agent_checkpoints_thread_id
  ON public.agent_checkpoints(thread_id);

-- Index for timestamp-based queries (checkpoint history)
CREATE INDEX IF NOT EXISTS idx_agent_checkpoints_created_at
  ON public.agent_checkpoints(thread_id, created_at DESC);

-- Index for parent checkpoint lookups (checkpoint chain)
CREATE INDEX IF NOT EXISTS idx_agent_checkpoints_parent
  ON public.agent_checkpoints(parent_checkpoint_id);

-- Enable Row Level Security
ALTER TABLE public.agent_checkpoints ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only access their own session checkpoints
-- Thread IDs should be based on session IDs which are tied to users
CREATE POLICY "Users can manage their own checkpoints"
  ON public.agent_checkpoints
  FOR ALL
  USING (
    -- Extract session_id from thread_id (format: session-{session_id})
    EXISTS (
      SELECT 1 FROM public.sessions
      WHERE sessions.id::text = substring(thread_id from 'session-(.+)')
      AND sessions.player_id = auth.uid()
    )
  );

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_agent_checkpoint_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update timestamp on checkpoint updates
CREATE TRIGGER update_agent_checkpoint_timestamp
  BEFORE UPDATE ON public.agent_checkpoints
  FOR EACH ROW
  EXECUTE FUNCTION public.update_agent_checkpoint_timestamp();

-- Add comment for documentation
COMMENT ON TABLE public.agent_checkpoints IS
  'Stores LangGraph checkpoint state for agent conversations. Replaces custom IndexedDB persistence.';

COMMENT ON COLUMN public.agent_checkpoints.thread_id IS
  'Thread identifier, typically in format: session-{session_id}';

COMMENT ON COLUMN public.agent_checkpoints.checkpoint_id IS
  'Unique checkpoint identifier generated by LangGraph';

COMMENT ON COLUMN public.agent_checkpoints.state IS
  'Serialized LangGraph state including messages and graph state';

COMMENT ON COLUMN public.agent_checkpoints.metadata IS
  'Additional metadata about the checkpoint (parent_id, step count, etc.)';
